Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Professor",
            "name": "Professor",
            "summary": "Summary\u0020of\u0020Professor",
            "url": "classes/App-Library-Domain-Entities-Professor.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Professor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "m\u00E9todo\u0020construtor\u0020de\u0020Professor\u0020um\u0020usu\u00E1rio\u0020que\u0020a\u0020ele\u0020\u00E9\u0020permitido\u0020fazer\u0020at\u00E9\u00203\u0020empr\u00E9stimos",
            "url": "classes/App-Library-Domain-Entities-Professor.html#method___construct"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Professor\u003A\u003AcanTakeOutMoreLoans\u0028\u0029",
            "name": "canTakeOutMoreLoans",
            "summary": "The\u0020user\u0020can\u0020take\u0020out\u0020more\u0020loans",
            "url": "classes/App-Library-Domain-Entities-Professor.html#method_canTakeOutMoreLoans"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role",
            "name": "Role",
            "summary": "",
            "url": "classes/App-Library-Domain-Entities-Role.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Summary\u0020of\u0020id",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Summary\u0020of\u0020id",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Summary\u0020of\u0020name",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_getName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Summary\u0020of\u0020name",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_setName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Summary\u0020of\u0020id",
            "url": "classes/App-Library-Domain-Entities-Role.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Summary\u0020of\u0020name",
            "url": "classes/App-Library-Domain-Entities-Role.html#property_name"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Student",
            "name": "Student",
            "summary": "",
            "url": "classes/App-Library-Domain-Entities-Student.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Student\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Library-Domain-Entities-Student.html#method___construct"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Student\u003A\u003AcanTakeOutMoreLoans\u0028\u0029",
            "name": "canTakeOutMoreLoans",
            "summary": "The\u0020user\u0020can\u0020take\u0020out\u0020more\u0020loans",
            "url": "classes/App-Library-Domain-Entities-Student.html#method_canTakeOutMoreLoans"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Library-Domain-Entities-User.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Username",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Username",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "User\u0020email",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "User\u0020email",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetRegistration\u0028\u0029",
            "name": "getRegistration",
            "summary": "User\u0020registration",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getRegistration"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetRegistration\u0028\u0029",
            "name": "setRegistration",
            "summary": "User\u0020registration",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setRegistration"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetRole\u0028\u0029",
            "name": "getRole",
            "summary": "User\u0020role",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getRole"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetRole\u0028\u0029",
            "name": "setRole",
            "summary": "User\u0020role",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setRole"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetLoanAmount\u0028\u0029",
            "name": "getLoanAmount",
            "summary": "user\u0020loan\u0020amount",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getLoanAmount"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetLoanAmount\u0028\u0029",
            "name": "setLoanAmount",
            "summary": "user\u0020loan\u0020amount",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setLoanAmount"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AcanTakeOutMoreLoans\u0028\u0029",
            "name": "canTakeOutMoreLoans",
            "summary": "The\u0020user\u0020can\u0020take\u0020out\u0020more\u0020loans",
            "url": "classes/App-Library-Domain-Entities-User.html#method_canTakeOutMoreLoans"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "User\u0020id",
            "url": "classes/App-Library-Domain-Entities-User.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Username",
            "url": "classes/App-Library-Domain-Entities-User.html#property_name"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "User\u0020email",
            "url": "classes/App-Library-Domain-Entities-User.html#property_email"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024registration",
            "name": "registration",
            "summary": "User\u0020registration",
            "url": "classes/App-Library-Domain-Entities-User.html#property_registration"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024loanAmount",
            "name": "loanAmount",
            "summary": "user\u0020loan\u0020amount",
            "url": "classes/App-Library-Domain-Entities-User.html#property_loanAmount"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024role",
            "name": "role",
            "summary": "Summary\u0020of\u0020role",
            "url": "classes/App-Library-Domain-Entities-User.html#property_role"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities",
            "name": "Entities",
            "summary": "",
            "url": "namespaces/app-library-domain-entities.html"
        },                {
            "fqsen": "\\App\\Library\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/app-library-domain.html"
        },                {
            "fqsen": "\\App\\Library",
            "name": "Library",
            "summary": "",
            "url": "namespaces/app-library.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
