Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book",
            "name": "Book",
            "summary": "Class\u0020Book",
            "url": "classes/App-Library-Domain-Entities-Book.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020book\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Sets\u0020the\u0020book\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Gets\u0020the\u0020book\u0020title",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020the\u0020book\u0020title",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AgetAuthor\u0028\u0029",
            "name": "getAuthor",
            "summary": "Gets\u0020the\u0020book\u0020author",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_getAuthor"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AsetAuthor\u0028\u0029",
            "name": "setAuthor",
            "summary": "Sets\u0020the\u0020book\u0020author",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_setAuthor"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AgetIsbn\u0028\u0029",
            "name": "getIsbn",
            "summary": "Gets\u0020the\u0020book\u0020ISBN",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_getIsbn"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AsetIsbn\u0028\u0029",
            "name": "setIsbn",
            "summary": "Sets\u0020the\u0020book\u0020ISBN",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_setIsbn"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AgetSection\u0028\u0029",
            "name": "getSection",
            "summary": "Gets\u0020the\u0020book\u0020section",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_getSection"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003AsetSection\u0028\u0029",
            "name": "setSection",
            "summary": "Sets\u0020the\u0020book\u0020section",
            "url": "classes/App-Library-Domain-Entities-Book.html#method_setSection"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Book\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Book.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003A\u0024title",
            "name": "title",
            "summary": "Book\u0020title",
            "url": "classes/App-Library-Domain-Entities-Book.html#property_title"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003A\u0024author",
            "name": "author",
            "summary": "Book\u0020author",
            "url": "classes/App-Library-Domain-Entities-Book.html#property_author"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003A\u0024isbn",
            "name": "isbn",
            "summary": "Book\u0020ISBN",
            "url": "classes/App-Library-Domain-Entities-Book.html#property_isbn"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Book\u003A\u003A\u0024section",
            "name": "section",
            "summary": "Book\u0020section",
            "url": "classes/App-Library-Domain-Entities-Book.html#property_section"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\ISBN",
            "name": "ISBN",
            "summary": "Class\u0020ISBN",
            "url": "classes/App-Library-Domain-Entities-ISBN.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\ISBN\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Gets\u0020the\u0020ISBN\u0020value",
            "url": "classes/App-Library-Domain-Entities-ISBN.html#method_getValue"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\ISBN\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Sets\u0020the\u0020ISBN\u0020value",
            "url": "classes/App-Library-Domain-Entities-ISBN.html#method_setValue"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\ISBN\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "Checks\u0020equality\u0020with\u0020another\u0020ISBN\u0020object",
            "url": "classes/App-Library-Domain-Entities-ISBN.html#method_equals"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\ISBN\u003A\u003A\u0024value",
            "name": "value",
            "summary": "The\u0020value\u0020of\u0020the\u0020ISBN",
            "url": "classes/App-Library-Domain-Entities-ISBN.html#property_value"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan",
            "name": "Loan",
            "summary": "Class\u0020Loan",
            "url": "classes/App-Library-Domain-Entities-Loan.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020loan\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Sets\u0020the\u0020loan\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AgetDateLoan\u0028\u0029",
            "name": "getDateLoan",
            "summary": "Gets\u0020the\u0020loan\u0020date",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_getDateLoan"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AsetDateLoan\u0028\u0029",
            "name": "setDateLoan",
            "summary": "Sets\u0020the\u0020loan\u0020date",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_setDateLoan"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AgetReturnLoan\u0028\u0029",
            "name": "getReturnLoan",
            "summary": "Gets\u0020the\u0020return\u0020date",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_getReturnLoan"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AsetReturnLoan\u0028\u0029",
            "name": "setReturnLoan",
            "summary": "Sets\u0020the\u0020return\u0020date",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_setReturnLoan"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "Gets\u0020user\u0020who\u0020made\u0020the\u0020loan",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_getUser"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "Sets\u0020user\u0020who\u0020made\u0020the\u0020loan",
            "url": "classes/App-Library-Domain-Entities-Loan.html#method_setUser"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Loan\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Loan.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003A\u0024dateLoan",
            "name": "dateLoan",
            "summary": "Loan\u0020date",
            "url": "classes/App-Library-Domain-Entities-Loan.html#property_dateLoan"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003A\u0024returnLoan",
            "name": "returnLoan",
            "summary": "Return\u0020date",
            "url": "classes/App-Library-Domain-Entities-Loan.html#property_returnLoan"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Loan\u003A\u003A\u0024user",
            "name": "user",
            "summary": "User\u0020who\u0020made\u0020the\u0020loan",
            "url": "classes/App-Library-Domain-Entities-Loan.html#property_user"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Professor",
            "name": "Professor",
            "summary": "Class\u0020Professor",
            "url": "classes/App-Library-Domain-Entities-Professor.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Professor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020of\u0020the\u0020Professor\u0020class",
            "url": "classes/App-Library-Domain-Entities-Professor.html#method___construct"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Professor\u003A\u003AcanTakeOutMoreLoans\u0028\u0029",
            "name": "canTakeOutMoreLoans",
            "summary": "Checks\u0020if\u0020the\u0020professor\u0020can\u0020make\u0020more\u0020loans",
            "url": "classes/App-Library-Domain-Entities-Professor.html#method_canTakeOutMoreLoans"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role",
            "name": "Role",
            "summary": "Class\u0020Role",
            "url": "classes/App-Library-Domain-Entities-Role.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020role\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Sets\u0020the\u0020role\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Gets\u0020the\u0020role\u0020name",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_getName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Sets\u0020the\u0020role\u0020name",
            "url": "classes/App-Library-Domain-Entities-Role.html#method_setName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Role\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Role.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Role\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Role\u0020name",
            "url": "classes/App-Library-Domain-Entities-Role.html#property_name"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section",
            "name": "Section",
            "summary": "Class\u0020Section",
            "url": "classes/App-Library-Domain-Entities-Section.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020section\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Section.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Sets\u0020the\u0020section\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Section.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003AgetLocalizator\u0028\u0029",
            "name": "getLocalizator",
            "summary": "Gets\u0020the\u0020section\u0020localizator",
            "url": "classes/App-Library-Domain-Entities-Section.html#method_getLocalizator"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003AsetLocalizator\u0028\u0029",
            "name": "setLocalizator",
            "summary": "Sets\u0020the\u0020section\u0020localizator",
            "url": "classes/App-Library-Domain-Entities-Section.html#method_setLocalizator"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Gets\u0020the\u0020section\u0020description",
            "url": "classes/App-Library-Domain-Entities-Section.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "Sets\u0020the\u0020section\u0020description",
            "url": "classes/App-Library-Domain-Entities-Section.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Section\u0020ID",
            "url": "classes/App-Library-Domain-Entities-Section.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003A\u0024localizator",
            "name": "localizator",
            "summary": "Section\u0020localizator",
            "url": "classes/App-Library-Domain-Entities-Section.html#property_localizator"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Section\u003A\u003A\u0024description",
            "name": "description",
            "summary": "Section\u0020description",
            "url": "classes/App-Library-Domain-Entities-Section.html#property_description"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Student",
            "name": "Student",
            "summary": "Class\u0020Student",
            "url": "classes/App-Library-Domain-Entities-Student.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Student\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020of\u0020the\u0020Student\u0020class",
            "url": "classes/App-Library-Domain-Entities-Student.html#method___construct"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\Student\u003A\u003AcanTakeOutMoreLoans\u0028\u0029",
            "name": "canTakeOutMoreLoans",
            "summary": "Checks\u0020if\u0020the\u0020student\u0020can\u0020make\u0020more\u0020loans",
            "url": "classes/App-Library-Domain-Entities-Student.html#method_canTakeOutMoreLoans"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User",
            "name": "User",
            "summary": "Class\u0020User",
            "url": "classes/App-Library-Domain-Entities-User.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020user\u0020ID",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "Sets\u0020the\u0020user\u0020ID",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setId"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Gets\u0020the\u0020username",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Sets\u0020the\u0020username",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setName"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "Gets\u0020the\u0020user\u0020email",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "Sets\u0020the\u0020user\u0020email",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetRegistration\u0028\u0029",
            "name": "getRegistration",
            "summary": "Gets\u0020the\u0020user\u0020registration",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getRegistration"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetRegistration\u0028\u0029",
            "name": "setRegistration",
            "summary": "Sets\u0020the\u0020user\u0020registration",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setRegistration"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetRole\u0028\u0029",
            "name": "getRole",
            "summary": "Gets\u0020the\u0020user\u0020role",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getRole"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetRole\u0028\u0029",
            "name": "setRole",
            "summary": "Sets\u0020the\u0020user\u0020role",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setRole"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AgetLoanAmount\u0028\u0029",
            "name": "getLoanAmount",
            "summary": "Gets\u0020the\u0020number\u0020of\u0020loans\u0020the\u0020user\u0020can\u0020make",
            "url": "classes/App-Library-Domain-Entities-User.html#method_getLoanAmount"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AsetLoanAmount\u0028\u0029",
            "name": "setLoanAmount",
            "summary": "Sets\u0020the\u0020number\u0020of\u0020loans\u0020the\u0020user\u0020can\u0020make",
            "url": "classes/App-Library-Domain-Entities-User.html#method_setLoanAmount"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003AcanTakeOutMoreLoans\u0028\u0029",
            "name": "canTakeOutMoreLoans",
            "summary": "Checks\u0020if\u0020the\u0020user\u0020can\u0020make\u0020more\u0020loans",
            "url": "classes/App-Library-Domain-Entities-User.html#method_canTakeOutMoreLoans"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "User\u0020ID",
            "url": "classes/App-Library-Domain-Entities-User.html#property_id"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024name",
            "name": "name",
            "summary": "Username",
            "url": "classes/App-Library-Domain-Entities-User.html#property_name"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "User\u0020email",
            "url": "classes/App-Library-Domain-Entities-User.html#property_email"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024registration",
            "name": "registration",
            "summary": "User\u0020registration",
            "url": "classes/App-Library-Domain-Entities-User.html#property_registration"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024loanAmount",
            "name": "loanAmount",
            "summary": "Number\u0020of\u0020loans\u0020the\u0020user\u0020can\u0020make",
            "url": "classes/App-Library-Domain-Entities-User.html#property_loanAmount"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities\\User\u003A\u003A\u0024role",
            "name": "role",
            "summary": "User\u0020role",
            "url": "classes/App-Library-Domain-Entities-User.html#property_role"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Library\\Domain\\Entities",
            "name": "Entities",
            "summary": "",
            "url": "namespaces/app-library-domain-entities.html"
        },                {
            "fqsen": "\\App\\Library\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/app-library-domain.html"
        },                {
            "fqsen": "\\App\\Library",
            "name": "Library",
            "summary": "",
            "url": "namespaces/app-library.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
